### ISSUE TITLE
percentage bug still not fixed 💀

### ISSUE THREAD

**Issue by archisha69** [thatOneArchUser/hydungeon#9]
https://media.discordapp.net/attachments/984714465071206422/996758857332314152/Screenshot_20220713-204343.png

**Comment by archisha69** [comment]
> This media.discordapp.net page can’t be found No webpage was found for the web address: https://media.discordapp.net/attachments/984714465071206422/996758857332314152/Screenshot_20220713-204343.png
> 
> HTTP ERROR 404

just meant the percentage in ur level where it wont level up

**Comment by thatOneArchUser** [comment]
bro idk how to fix that

**Comment by archisha69** [comment]
> bro idk how to fix that

K then, won't fix .-.
